# -*- coding: utf-8 -*-
"""CMP7005_PRAC1_Fraud_Detection_Complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRAvvSZhjn7_jFMEyEMMraqwLPfU0r1L

# Fraud Detection Analysis for CMP7005 PRAC1
**Name:** Fathima Aabidha Rifky  
**Cardiff Met ID:** st20357374  
**ICBT ID:** CL-MCSDS-CMU-10-04
"""

import warnings, joblib
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score,
    roc_curve, auc, precision_recall_curve, average_precision_score
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

for folder in ["figures", "tables", "logs", "models", "reports"]:
    Path(folder).mkdir(parents=True, exist_ok=True)

print("Output folders created successfully.")

def find_file(patterns):
    search_roots = [Path("."), Path("/mnt/data")]
    matches = []
    for root in search_roots:
        for pattern in patterns:
            matches.extend(root.glob(pattern))
    matches = [m for m in matches if m.is_file()]
    if not matches:
        raise FileNotFoundError(f"No file found for patterns: {patterns}")
    matches = sorted(matches, key=lambda p: (len(str(p)), str(p)))
    return matches[0]

file1 = find_file(["*Credit*Sept_1*.csv", "*Credir*Sept_1*.csv"])
file2 = find_file(["*Credit*Sept_2*.csv", "*Credir*Sept_2*.csv"])

print("Dataset 1:", file1)
print("Dataset 2:", file2)

data_1 = pd.read_csv(file1)
data_2 = pd.read_csv(file2)

print("Dataset 1 shape:", data_1.shape)
print("Dataset 2 shape:", data_2.shape)
print("\nDataset 1 columns:", list(data_1.columns))
print("\nDataset 2 columns:", list(data_2.columns))

data = pd.merge(data_1, data_2, left_on="ID", right_on="User", how="outer")
print("\nMerged dataset shape:", data.shape)
display(data.head())

with open("logs/data_loading_and_merging_log.txt", "w") as f:
    f.write(f"Dataset 1 path: {file1}\n")
    f.write(f"Dataset 2 path: {file2}\n")
    f.write(f"Dataset 1 shape: {data_1.shape}\n")
    f.write(f"Dataset 2 shape: {data_2.shape}\n")
    f.write(f"Merged shape: {data.shape}\n")

"""## Task 2A – Data understanding"""

dataset_shape = pd.DataFrame({"Metric": ["Rows", "Columns"], "Value": [data.shape[0], data.shape[1]]})
column_audit = pd.DataFrame({
    "Column": data.columns,
    "Data_Type": data.dtypes.astype(str).values,
    "Missing_Values": data.isnull().sum().values,
    "Missing_Percentage": (data.isnull().sum().values / len(data) * 100).round(3),
    "Unique_Values": [data[col].nunique(dropna=False) for col in data.columns]
}).sort_values(by=["Missing_Values", "Unique_Values"], ascending=[False, False])

dataset_shape.to_csv("tables/dataset_shape_summary.csv", index=False)
column_audit.to_csv("tables/column_audit_summary.csv", index=False)

display(dataset_shape)
display(column_audit)

duplicate_full_rows = int(data.duplicated().sum())
duplicate_id_rows = int(data["ID"].duplicated().sum()) if "ID" in data.columns else np.nan

duplicate_summary = pd.DataFrame({"Metric": ["Duplicate full rows", "Duplicate ID values"], "Value": [duplicate_full_rows, duplicate_id_rows]})
duplicate_summary.to_csv("tables/duplicate_summary.csv", index=False)
display(duplicate_summary)

if duplicate_full_rows > 0:
    data = data.drop_duplicates().copy()

print("Shape after duplicate handling:", data.shape)

missing_summary_before = pd.DataFrame({"Column": data.columns, "Missing_Count": data.isnull().sum().values})
missing_summary_before["Missing_Percentage"] = (missing_summary_before["Missing_Count"] / len(data) * 100).round(3)
missing_summary_before = missing_summary_before.sort_values(by="Missing_Count", ascending=False)

missing_summary_before.to_csv("tables/missing_summary_before_treatment.csv", index=False)
display(missing_summary_before)

missing_nonzero = missing_summary_before[missing_summary_before["Missing_Count"] > 0]
if len(missing_nonzero) > 0:
    plt.figure(figsize=(10, 5))
    plt.bar(missing_nonzero["Column"], missing_nonzero["Missing_Count"])
    plt.title("Missing Values Before Treatment")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig("figures/missing_values_before_treatment.png", dpi=300, bbox_inches="tight")
    plt.show()
else:
    print("No missing values detected before treatment.")

"""## Task 2B – Preprocessing"""

data_clean = data.copy()

numeric_columns = data_clean.select_dtypes(include=[np.number]).columns.tolist()
categorical_columns = data_clean.select_dtypes(exclude=[np.number]).columns.tolist()

for col in numeric_columns:
    data_clean[col] = data_clean[col].fillna(data_clean[col].median())

for col in categorical_columns:
    mode_value = data_clean[col].mode(dropna=True)
    fill_value = mode_value.iloc[0] if len(mode_value) > 0 else "Unknown"
    data_clean[col] = data_clean[col].fillna(fill_value)

missing_summary_after = pd.DataFrame({"Column": data_clean.columns, "Missing_Count": data_clean.isnull().sum().values})
missing_summary_after["Missing_Percentage"] = (missing_summary_after["Missing_Count"] / len(data_clean) * 100).round(3)
missing_summary_after.to_csv("tables/missing_summary_after_treatment.csv", index=False)
display(missing_summary_after.sort_values(by="Missing_Count", ascending=False).head(20))

candidate_numeric_cols = [col for col in ["NO_OF_CHILD", "FAMILY SIZE", "BEGIN_MONTH", "AGE", "YEARS_EMPLOYED", "INCOME"] if col in data_clean.columns]

data_capped = data_clean.copy()
outlier_records = []

for col in candidate_numeric_cols:
    q1 = data_capped[col].quantile(0.25)
    q3 = data_capped[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outlier_count = int(((data_capped[col] < lower_bound) | (data_capped[col] > upper_bound)).sum())
    outlier_records.append({
        "Column": col,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Outlier_Count_Before_Capping": outlier_count,
        "Outlier_Percentage_Before_Capping": round(outlier_count / len(data_capped) * 100, 3)
    })
    data_capped[col] = data_capped[col].clip(lower=lower_bound, upper=upper_bound)

outlier_summary = pd.DataFrame(outlier_records)
outlier_summary.to_csv("tables/outlier_summary.csv", index=False)
display(outlier_summary)

plt.figure(figsize=(16, 10))
for i, col in enumerate(candidate_numeric_cols, 1):
    plt.subplot(2, 3, i)
    plt.boxplot(data_capped[col].dropna(), vert=True)
    plt.title(f"Boxplot: {col}")

plt.tight_layout()
plt.savefig("figures/boxplots_after_outlier_capping.png", dpi=300, bbox_inches="tight")
plt.show()

"""## Task 2C – Statistical analysis and visualisation"""

numerical_stats = data_capped.describe(include=[np.number]).T
numerical_stats.to_csv("tables/numerical_statistics.csv")
display(numerical_stats)

categorical_summary = []
for col in data_capped.select_dtypes(exclude=[np.number]).columns:
    vc = data_capped[col].value_counts(dropna=False)
    categorical_summary.append({
        "Column": col,
        "Most_Frequent_Value": vc.index[0] if len(vc) > 0 else np.nan,
        "Frequency": vc.iloc[0] if len(vc) > 0 else np.nan
    })

categorical_summary_df = pd.DataFrame(categorical_summary)
categorical_summary_df.to_csv("tables/categorical_summary.csv", index=False)
display(categorical_summary_df)

class_distribution = data_capped["TARGET"].value_counts().sort_index()
class_distribution_df = class_distribution.rename_axis("TARGET").reset_index(name="Count")
class_distribution_df["Percentage"] = (class_distribution_df["Count"] / len(data_capped) * 100).round(3)
class_distribution_df.to_csv("tables/class_distribution.csv", index=False)
display(class_distribution_df)

plt.figure(figsize=(6, 5))
plt.bar(class_distribution_df["TARGET"].astype(str), class_distribution_df["Count"])
plt.title("Target Class Distribution")
plt.xlabel("Target (0 = Non-Fraud, 1 = Fraud)")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("figures/target_class_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

numeric_plot_cols = [col for col in ["INCOME", "AGE", "YEARS_EMPLOYED", "BEGIN_MONTH"] if col in data_capped.columns]

plt.figure(figsize=(14, 10))
for i, col in enumerate(numeric_plot_cols, 1):
    plt.subplot(2, 2, i)
    plt.hist(data_capped[col].dropna(), bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")

plt.tight_layout()
plt.savefig("figures/numerical_distributions.png", dpi=300, bbox_inches="tight")
plt.show()

categorical_plot_cols = [col for col in ["GENDER", "CAR", "FAMILY_TYPE", "HOUSE_TYPE", "INCOME_TYPE", "EDUCATION_TYPE"] if col in data_capped.columns]

ncols = 2
nrows = int(np.ceil(len(categorical_plot_cols) / ncols))

plt.figure(figsize=(16, 5 * nrows))
for i, col in enumerate(categorical_plot_cols, 1):
    plt.subplot(nrows, ncols, i)
    counts = data_capped[col].value_counts()
    plt.bar(counts.index.astype(str), counts.values)
    plt.title(f"{col} Distribution")
    plt.xticks(rotation=30, ha="right")
    plt.ylabel("Count")

plt.tight_layout()
plt.savefig("figures/categorical_distributions.png", dpi=300, bbox_inches="tight")
plt.show()

numeric_data = data_capped.select_dtypes(include=[np.number]).copy()
constant_cols = [col for col in numeric_data.columns if numeric_data[col].nunique() <= 1]
if constant_cols:
    numeric_data = numeric_data.drop(columns=constant_cols)

correlation_matrix = numeric_data.corr()
correlation_matrix.to_csv("tables/correlation_matrix.csv")

plt.figure(figsize=(12, 8))
plt.imshow(correlation_matrix, cmap="coolwarm", aspect="auto")
plt.colorbar()
plt.xticks(range(len(correlation_matrix.columns)), correlation_matrix.columns, rotation=90)
plt.yticks(range(len(correlation_matrix.index)), correlation_matrix.index)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("figures/correlation_heatmap.png", dpi=300, bbox_inches="tight")
plt.show()

"""## Task 3 – Model building"""

data_model = pd.get_dummies(data_capped, drop_first=True)

drop_candidate_cols = ["TARGET", "ID", "User", "Unnamed: 0"]
X = data_model.drop(columns=[c for c in drop_candidate_cols if c in data_model.columns], errors="ignore")
y = data_model["TARGET"].astype(int)

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)
X.head().to_csv("tables/model_feature_preview.csv", index=False)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

split_summary = pd.DataFrame({
    "Dataset": ["X_train", "X_test", "y_train", "y_test"],
    "Shape": [str(X_train.shape), str(X_test.shape), str(y_train.shape), str(y_test.shape)]
})
split_summary.to_csv("tables/train_test_split_summary.csv", index=False)
display(split_summary)

X_train.to_csv("tables/X_train.csv", index=False)
X_test.to_csv("tables/X_test.csv", index=False)
y_train.to_csv("tables/y_train.csv", index=False)
y_test.to_csv("tables/y_test.csv", index=False)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
joblib.dump(scaler, "models/standard_scaler.pkl")
print("Scaling complete.")

def evaluate_model(model_name, y_true, y_pred, y_prob=None):
    result = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1_Score": f1_score(y_true, y_pred, zero_division=0),
        "ROC_AUC": roc_auc_score(y_true, y_prob) if y_prob is not None else np.nan
    }
    metrics_df = pd.DataFrame([result])
    metrics_df.to_csv(f"tables/{model_name}_metrics.csv", index=False)

    with open(f"logs/{model_name}_classification_report.txt", "w") as f:
        f.write(classification_report(y_true, y_pred, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    pd.DataFrame(cm, index=["Actual_0", "Actual_1"], columns=["Pred_0", "Pred_1"]).to_csv(f"tables/{model_name}_confusion_matrix.csv")

    plt.figure(figsize=(5, 4))
    plt.imshow(cm, cmap="Blues")
    plt.colorbar()
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.xticks([0,1], ["Pred_0","Pred_1"])
    plt.yticks([0,1], ["Actual_0","Actual_1"])
    plt.title(f"{model_name} Confusion Matrix")
    plt.tight_layout()
    plt.savefig(f"figures/{model_name}_confusion_matrix.png", dpi=300, bbox_inches="tight")
    plt.show()
    return metrics_df

lr_baseline = LogisticRegression(max_iter=2000, random_state=42)
lr_baseline.fit(X_train_scaled, y_train)
y_pred_lr_baseline = lr_baseline.predict(X_test_scaled)
y_prob_lr_baseline = lr_baseline.predict_proba(X_test_scaled)[:, 1]
lr_baseline_results = evaluate_model("logistic_regression_baseline", y_test, y_pred_lr_baseline, y_prob_lr_baseline)

lr_weighted = LogisticRegression(max_iter=2000, random_state=42, class_weight="balanced")
lr_weighted.fit(X_train_scaled, y_train)
y_pred_lr_weighted = lr_weighted.predict(X_test_scaled)
y_prob_lr_weighted = lr_weighted.predict_proba(X_test_scaled)[:, 1]
lr_weighted_results = evaluate_model("logistic_regression_weighted", y_test, y_pred_lr_weighted, y_prob_lr_weighted)

joblib.dump(lr_baseline, "models/logistic_regression_baseline.pkl")
joblib.dump(lr_weighted, "models/logistic_regression_weighted.pkl")
display(pd.concat([lr_baseline_results, lr_weighted_results], ignore_index=True))

dt_baseline = DecisionTreeClassifier(random_state=42)
dt_baseline.fit(X_train, y_train)
y_pred_dt_baseline = dt_baseline.predict(X_test)
y_prob_dt_baseline = dt_baseline.predict_proba(X_test)[:, 1]
dt_baseline_results = evaluate_model("decision_tree_baseline", y_test, y_pred_dt_baseline, y_prob_dt_baseline)

dt_weighted = DecisionTreeClassifier(random_state=42, class_weight="balanced")
dt_weighted.fit(X_train, y_train)
y_pred_dt_weighted = dt_weighted.predict(X_test)
y_prob_dt_weighted = dt_weighted.predict_proba(X_test)[:, 1]
dt_weighted_results = evaluate_model("decision_tree_weighted", y_test, y_pred_dt_weighted, y_prob_dt_weighted)

joblib.dump(dt_baseline, "models/decision_tree_baseline.pkl")
joblib.dump(dt_weighted, "models/decision_tree_weighted.pkl")
display(pd.concat([dt_baseline_results, dt_weighted_results], ignore_index=True))

dt_param_grid = {
    "max_depth": [3, 5, 7, 10, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5],
    "criterion": ["gini", "entropy"]
}
cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

dt_grid = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    param_grid=dt_param_grid,
    scoring="f1",
    cv=cv_strategy,
    n_jobs=-1
)
dt_grid.fit(X_train, y_train)

best_dt = dt_grid.best_estimator_
best_dt_params = pd.DataFrame([dt_grid.best_params_])
best_dt_params["Best_CV_F1"] = dt_grid.best_score_
best_dt_params.to_csv("tables/best_decision_tree_parameters.csv", index=False)
display(best_dt_params)

y_pred_best_dt = best_dt.predict(X_test)
y_prob_best_dt = best_dt.predict_proba(X_test)[:, 1]
dt_tuned_results = evaluate_model("decision_tree_tuned", y_test, y_pred_best_dt, y_prob_best_dt)
joblib.dump(best_dt, "models/decision_tree_tuned.pkl")
display(dt_tuned_results)

cv_results = []

lr_weighted_cv = cross_val_score(
    LogisticRegression(max_iter=2000, random_state=42, class_weight="balanced"),
    X_train_scaled, y_train, cv=cv_strategy, scoring="f1", n_jobs=-1
)
cv_results.append({"Model": "Logistic Regression Weighted", "CV_F1_Mean": lr_weighted_cv.mean(), "CV_F1_STD": lr_weighted_cv.std()})

dt_weighted_cv = cross_val_score(
    DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    X_train, y_train, cv=cv_strategy, scoring="f1", n_jobs=-1
)
cv_results.append({"Model": "Decision Tree Weighted", "CV_F1_Mean": dt_weighted_cv.mean(), "CV_F1_STD": dt_weighted_cv.std()})

dt_tuned_cv = cross_val_score(best_dt, X_train, y_train, cv=cv_strategy, scoring="f1", n_jobs=-1)
cv_results.append({"Model": "Decision Tree Tuned", "CV_F1_Mean": dt_tuned_cv.mean(), "CV_F1_STD": dt_tuned_cv.std()})

cv_results_df = pd.DataFrame(cv_results)
cv_results_df.to_csv("tables/cross_validation_results.csv", index=False)
display(cv_results_df)

final_results = pd.concat([
    lr_baseline_results,
    lr_weighted_results,
    dt_baseline_results,
    dt_weighted_results,
    dt_tuned_results
], ignore_index=True).sort_values(by="F1_Score", ascending=False)

final_results.to_csv("tables/final_model_comparison.csv", index=False)
display(final_results)

model_probabilities = {"LR Weighted": y_prob_lr_weighted, "DT Weighted": y_prob_dt_weighted, "DT Tuned": y_prob_best_dt}

plt.figure(figsize=(8, 6))
for name, probs in model_probabilities.items():
    fpr, tpr, _ = roc_curve(y_test, probs)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.3f})")
plt.plot([0,1],[0,1],"--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.tight_layout()
plt.savefig("figures/roc_curve_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 6))
for name, probs in model_probabilities.items():
    precision, recall, _ = precision_recall_curve(y_test, probs)
    ap = average_precision_score(y_test, probs)
    plt.plot(recall, precision, label=f"{name} (AP = {ap:.3f})")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve Comparison")
plt.legend()
plt.tight_layout()
plt.savefig("figures/precision_recall_curve_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

feature_importance = pd.DataFrame({"Feature": X.columns, "Importance": best_dt.feature_importances_}).sort_values(by="Importance", ascending=False)
feature_importance.to_csv("tables/decision_tree_feature_importance.csv", index=False)
top_features = feature_importance.head(15)

plt.figure(figsize=(10, 6))
plt.barh(top_features["Feature"], top_features["Importance"])
plt.gca().invert_yaxis()
plt.title("Top 15 Feature Importances - Tuned Decision Tree")
plt.tight_layout()
plt.savefig("figures/top15_feature_importance_tuned_dt.png", dpi=300, bbox_inches="tight")
plt.show()

display(top_features)

completion_checklist = pd.DataFrame([
    ["Task 1 - Dataset import", "Done"],
    ["Task 1 - Dataset merge", "Done"],
    ["Task 2A - Shape, columns, data types", "Done"],
    ["Task 2A - Missing value analysis", "Done"],
    ["Task 2A - Unique value summary", "Done"],
    ["Task 2B - Missing value treatment", "Done"],
    ["Task 2B - Duplicate analysis", "Done"],
    ["Task 2B - Outlier analysis", "Done"],
    ["Task 2B - Outlier capping", "Done"],
    ["Task 2B - Encoding", "Done"],
    ["Task 2C - Descriptive statistics", "Done"],
    ["Task 2C - Numerical visualisations", "Done"],
    ["Task 2C - Categorical visualisations", "Done"],
    ["Task 2C - Correlation heatmap", "Done"],
    ["Task 3 - Logistic Regression", "Done"],
    ["Task 3 - Decision Tree", "Done"],
    ["Task 3 - Metrics comparison", "Done"],
    ["Task 3 - Model improvement using tuning", "Done"],
    ["Task 3 - Cross-validation", "Done"],
    ["Task 4 - GUI", "Not included in this notebook"],
    ["Task 5 - GitHub screenshot evidence", "To be added manually"]
], columns=["Requirement", "Status"])

completion_checklist.to_csv("tables/completion_checklist.csv", index=False)
display(completion_checklist)

with open("reports/final_summary_report.txt", "w") as f:
    f.write("Fraud Detection Analysis Summary\n")
    f.write("="*50 + "\n\n")
    f.write(f"Merged dataset shape: {data.shape}\n")
    f.write(f"Feature matrix shape: {X.shape}\n\n")
    f.write("Class distribution:\n")
    f.write(class_distribution_df.to_string(index=False))
    f.write("\n\nFinal model comparison:\n")
    f.write(final_results.to_string(index=False))
    f.write("\n\nBest Decision Tree Parameters:\n")
    f.write(best_dt_params.to_string(index=False))
    f.write("\n\nCross-validation results:\n")
    f.write(cv_results_df.to_string(index=False))
print("Summary report saved successfully.")

print("Notebook executed successfully from top to bottom.")
print("Saved outputs in figures/, tables/, logs/, models/, and reports/.")